services:
  - type: web
    name: buzz-craft-socials
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn buzz_craft_socials.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: buzz_craft_socials.settings
