services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn PROJECT_NAME.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: PROJECT_NAME.settings
