services:
  - type: web
    name: buzz-craft-socials
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn buzz_craft_socials.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
